### ISSUE TITLE
Angular view/routes

### ISSUE THREAD

**Issue by andrewpei** [makersquare/pied-piper#27]
Need to take static html page link it to angular view and then create angular routes and link to angular router inside app.js

**Comment by TheBranchDriftCatalyst** [comment]
This is going to be a bit more complicated.  I added the NG routes dependency and created a routing file.  However we need to resolve the issues between ng-routes and rails routing.  Then we all need to get a quick tutorial on how this works; so we are all on the same page.  Rails Routes needs to be used in a certain way.

**Comment by TheBranchDriftCatalyst** [comment]
Directly from web:

As Angular is configured by default, it does not implement HTML5 pushState features. This means that absolute routes will still cause the browser to request the new page directly from the server.

**Comment by TheBranchDriftCatalyst** [comment]
Completed this, and also added foundation into the application.
