### ISSUE TITLE
Add collaborators to pipelines (and admins)

### ISSUE THREAD

**Issue by sdevani** [makersquare/pied-piper#58]

**Comment by andrewpei** [comment]
- Create template in angular templates 
- Modify the pipeline view to have manage collaborators button
- Write controller methods
- Write resource calls in factory format: need call to get collab data, call to update collab status, call to remove collab
- Connect angular w/rails, send the calls to the right methods in pipeline controller and pass in the needed params
- Have to not display the pipeline_collab button on show pipeline view if the user is not an admin

**Comment by andrewpei** [comment]
Done. Only thing which isn't done is a check to see if they are the pipline admin. This is blocked by authentication on the site issue
